server:
  servlet:
    context-path: /scheduling
  port: 8081
spring:
  data:
    mongodb:
      database: scheduling
      host: localhost
  cache:
    type: redis
  redis:
    host: "redis"
    port: 6379

