server:
  servlet:
    context-path: /scheduling
  port: 8080
spring:
  data:
    mongodb:
      database: scheduling
      host: app_db
  cache:
    type: redis
  redis:
    host: "redis"
    port: 6379

